import type {Metadata} from 'next'
// import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import NavBar from './ui/NavBar/NavBar'
import Footer from './ui/Footer/Footer'

// const geistSans = Geist({
// 	variable: '--font-geist-sans',
// 	subsets: ['latin']
// })

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin']
// })

export const metadata: Metadata = {
	title: 'Hector Sanchez',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			<body>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
